### PR TITLE
Client fixes

### PR DESCRIPTION
**Pull request by brianN0KZ**
Fixed Session.connect() checking for initialized when it can't be set
Fixed package.json pointing to incompatible SerialPort
Added kisspat.js example (use D74a over bluetooth to access CMS with pat)

### CODE REVIEW

**Comment by brianN0KZ** [comment]
I've built a reverse CMS gateway so that I can use pat with my D74a.  Fixed a bug in Session preventing connect().  Fixed a bug in package.json preventing connection to TNC.

**Comment by echicken** [comment]
I've been planning on redoing much of this module for quite some time.  The 'Session' portion in particular is not great and was just bashed out as a quick test for myself.  If it's working for you in its current state, that's great, but I'd like to destroy it and start again.

I see that I wasn't watching my language in an earlier commit message.  Thanks for coming along and wagging your finger at me, really warms the heart.

**Comment by brianN0KZ** [comment]
Not trying to wag a finger, but my work monitors my activity on github.  Polishing my nodejs skill is legitimate work, but the appearance of professionalism is required.  It’s not on you, but it is on me.  Sorry if that seems manipulative, it’s not my intention.   The github model of fork and pull means that the comments end up on my front page and I kind of need to clean it up to maintain appearances.  

Regarding a rebuild of Session.js I think there are lots of reasons to put in some effort, and I am happy to help.  I am debugging some issues with large sends, but I think it may be my D74a.  

I have been doing packet for 18 years, and node for 1, so I will do what I can. The only downside is that there are very few packet stations around here.  Debugging this is as I can.

I also think that bringing kissTNC.js up to date with latest SerialPort is worth doing (if only to reduce the pain for new users) but I know nothing about it. Yet.

**Comment by echicken** [comment]
I get it.  Frankly I never expected anyone to use this, and certainly didn't foresee this scenario.  Totally understood.

I would caution you against putting much work into this module right now.  Please see the note that I added to README.md this evening.

I wrote this thing four years ago, and looking at it now I can see that I didn't put much planning into it ahead of time.  I've just started a full rewrite, so you may want to hold off on improving this code (it needs a lot of work).  I'll probably be plugging away at this for the next little while.

My starting point now is a separate KISS TNC module, which I created today although it still needs some work.  It will live in its own space.  It's already fundamentally better than the existing one.

Next up will be AX.25 packet assembly/disassembly.  That's easy enough, but I hope to make it a bit less ugly this time around.

A new 'Session' class will follow.  This is the most annoying part, and it's the part of the current module that I have the least faith in.  I don't trust it to do error recovery acceptably, etc.  If I can follow along with the protocol spec a bit better this time, I'll get better results.  (I wish that document were organized differently, but what can you do.)

**Comment by echicken** [comment]
I should add that I'm also testing with a TH-D74a, and a TH-D7 on the other side (not in KISS mode, even if I wanted to KISS is broken on that model).  I think my TH-D74a is still on firmware 1.05, so I will probably update it tomorrow.

I also have a PK-232 and a KPC3+ kicking around here, so that's more stuff to test with.

**Pull request merged**
